hidpi
# export GDK_SCALE = 1
# export GDK_DPI_SCALE = 1
export QT_AUTO_SCREEN_SCALE_FACTOR = 1
# export QT_SCALE_FACTOR = 1
# export QT_SCREEN_SCALE_FACTOR = 1

# xrandr --dpi 226

# export LANG=zh_CN.UTF-8
# export LANGUAGE=zh_CN:en_US

Xft.dpi: 96
Xft.antialias: true      
Xft.hinting: true
Xft.rgba: rgb 
Xft.autohint: false
Xft.hintstyle: hintslight
Xft.lcdfilter: lcddefault

xrdb -merge ~/.Xresources
